import { PublicPortfolioBundle } from '../types/portfolio';

export const STATIC_OMAR_BUNDLE: PublicPortfolioBundle = {
  portfolio: {
    id: 'omar-portfolio-001',
    client_id: 'omar-client-001',
    slug: 'omar-mohamed-fawzi',
    name: 'Omar Mohamed Fawzi Portfolio',
    published: true,
    status: 'PUBLISHED',
    custom_domain: null,
    deleted_at: null,
    created_at: '2026-09-20T12:00:00.000Z',
    updated_at: '2026-09-20T12:00:00.000Z',
  },
  client: {
    id: 'omar-client-001',
    name: 'Omar Mohamed Fawzi',
    email: 'omar@ultimatetomato.com',
    status: 'ACTIVE',
    onboarding_token: null,
    onboarding_completed: true,
    deleted_at: null,
    created_at: '2026-09-20T12:00:00.000Z',
    updated_at: '2026-09-20T12:00:00.000Z',
  },
  settings: {
    id: 'omar-settings-001',
    portfolio_id: 'omar-portfolio-001',
    title: 'Omar Mohamed Fawzi — Creative Developer & Digital Builder',
    description:
      'Official portfolio of Omar Mohamed Fawzi, engineered by Ultimate Tomato. Specialized in high-performance web applications, modern SaaS interfaces, and creative engineering.',
    logo: './assets/ultimate-tomato-logo.png',
    favicon: './assets/ultimate-tomato-logo.png',
    primary_color: '#F52F3A',
    default_theme: 'dark',
    seo_title: 'Omar Mohamed Fawzi | Creative Developer Portfolio',
    seo_description:
      'Explore projects, case studies, and engineering craft by Omar Mohamed Fawzi. Built with Ultimate Tomato.',
    og_image: './assets/ultimate-tomato-logo.png',
    contact_email: 'omar@ultimatetomato.com',
    phone: '',
    location: 'Egypt / Remote Worldwide',
    bio: 'Creative full-stack developer dedicated to architecting ultra-clean, high-performance web experiences. Focused on minimalist aesthetics, fluid micro-interactions, robust TypeScript architectures, and purposeful engineering.',
    professional_title: 'Creative Developer & UI/UX Architect',
    portrait_url: '',
    resume_url: '',
    stats: {
      projects: 14,
      experience_years: 4,
      clients: 9,
      technologies: 18,
    },
    custom_domain: null,
    created_at: '2026-09-20T12:00:00.000Z',
    updated_at: '2026-09-20T12:00:00.000Z',
  },
  categories: [
    {
      id: 'cat-web-01',
      portfolio_id: 'omar-portfolio-001',
      name: 'Web Applications',
      slug: 'web-applications',
      description: 'High-performance modern web apps and scalable SaaS frontends.',
      sort_order: 1,
      visible: true,
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'cat-creative-02',
      portfolio_id: 'omar-portfolio-001',
      name: 'Creative Engineering',
      slug: 'creative-engineering',
      description: 'Interactive visuals, micro-interactions, and glassmorphic designs.',
      sort_order: 2,
      visible: true,
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'cat-ui-03',
      portfolio_id: 'omar-portfolio-001',
      name: 'Design Systems',
      slug: 'design-systems',
      description: 'Scalable UI components, tokenized design architectures, and accessible libraries.',
      sort_order: 3,
      visible: true,
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  projects: [
    {
      id: 'proj-01',
      portfolio_id: 'omar-portfolio-001',
      category_id: 'cat-web-01',
      title: 'Enterprise Cloud Platform',
      slug: 'enterprise-cloud-platform',
      short_description: 'Next-generation cloud infrastructure orchestration dashboard with real-time telemetry.',
      full_description:
        'A comprehensive cloud orchestration platform designed for enterprise scale. Features sub-second data streaming, interactive infrastructure graphs, role-based access control, and dark-mode-first glassmorphic interface.',
      client: 'CloudScale Global',
      date: '2026',
      technologies: ['React 19', 'TypeScript', 'Tailwind CSS', 'WebSockets', 'WebRTC'],
      tags: ['SaaS', 'Cloud', 'Real-Time'],
      featured: true,
      published: true,
      hero_image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=80',
      images: [
        {
          id: 'img-01',
          project_id: 'proj-01',
          image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
          alt_text: 'Analytics Overview Dashboard',
          sort_order: 1,
          created_at: '2026-09-20T12:00:00.000Z',
          updated_at: '2026-09-20T12:00:00.000Z',
        },
      ],
      project_url: 'https://omarmhmdfwzi22-hacker.github.io/ultimate-tomato/',
      github_url: 'https://github.com/omarmhmdfwzi22-hacker/ultimate-tomato',
      challenge:
        'Handling high-frequency metric streams while preserving a responsive, 60fps UI experience across dense monitoring grids.',
      solution:
        'Architected a decoupled render pipeline utilizing virtualized data grids, efficient memoization, and selective DOM updates.',
      results:
        'Delivered sub-50ms latency across 50,000 live nodes, cutting operational monitoring overhead by 40%.',
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'proj-02',
      portfolio_id: 'omar-portfolio-001',
      category_id: 'cat-creative-02',
      title: 'Aesthetic Creative Portfolio Engine',
      slug: 'creative-portfolio-engine',
      short_description: 'Fluid micro-interactions, responsive typography, and glassmorphic depth for modern creators.',
      full_description:
        'A tailored portfolio system built from the ground up prioritizing speed, editorial typographic rhythm, and delicate glassmorphism. Highlights smooth view transitions and accessible dark/light modes.',
      client: 'Ultimate Tomato Studio',
      date: '2026',
      technologies: ['React 19', 'TypeScript', 'Tailwind v4', 'Motion'],
      tags: ['Creative', 'UI/UX', 'Glassmorphism'],
      featured: true,
      published: true,
      hero_image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1400&q=80',
      images: [],
      project_url: 'https://omarmhmdfwzi22-hacker.github.io/ultimate-tomato/',
      github_url: 'https://github.com/omarmhmdfwzi22-hacker/ultimate-tomato',
      challenge:
        'Balancing heavy visual richness (backdrop blur, dynamic gradients, shadows) with strict Lighthouse 100 performance.',
      solution:
        'Engineered hardware-accelerated CSS properties, lazy-loaded off-screen modules, and optimized SVG iconography.',
      results:
        'Maintained 100 Lighthouse performance scores and sub-1 second first meaningful paint on mobile devices.',
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'proj-03',
      portfolio_id: 'omar-portfolio-001',
      category_id: 'cat-ui-03',
      title: 'Autonomous System UI Architecture',
      slug: 'autonomous-system-ui',
      short_description: 'Modern human-in-the-loop developer interfaces for autonomous coding agents and workflow orchestrators.',
      full_description:
        'An intuitive control surface designed for interacting with intelligent developer workflows. Offers rich terminal logs, interactive step visualization, and responsive state synchronization.',
      client: 'AI Systems Group',
      date: '2026',
      technologies: ['React 19', 'TypeScript', 'Tailwind', 'Express'],
      tags: ['AI/ML', 'Developer Tools', 'Frontend Architecture'],
      featured: true,
      published: true,
      hero_image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1400&q=80',
      images: [],
      project_url: 'https://omarmhmdfwzi22-hacker.github.io/ultimate-tomato/',
      github_url: 'https://github.com/omarmhmdfwzi22-hacker/ultimate-tomato',
      challenge:
        'Representing non-linear asynchronous agent execution trajectories clearly without overwhelming user attention.',
      solution:
        'Developed hierarchical execution cards with collapsible inspection drawers and color-coded status badges.',
      results:
        'Improved human oversight speed by 65% during complex multi-step build workflows.',
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  skills: [
    {
      id: 'skill-01',
      portfolio_id: 'omar-portfolio-001',
      name: 'TypeScript & JavaScript (ESNext)',
      category: 'Frontend & Architecture',
      level: 95,
      years: 4,
      sort_order: 1,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'skill-02',
      portfolio_id: 'omar-portfolio-001',
      name: 'React 19 & Next.js Architecture',
      category: 'Frontend & Architecture',
      level: 92,
      years: 4,
      sort_order: 2,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'skill-03',
      portfolio_id: 'omar-portfolio-001',
      name: 'Tailwind CSS & Glassmorphic UI Design',
      category: 'UI/UX & Styling',
      level: 95,
      years: 4,
      sort_order: 3,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'skill-04',
      portfolio_id: 'omar-portfolio-001',
      name: 'Node.js & Express REST Backend',
      category: 'Backend & APIs',
      level: 88,
      years: 3,
      sort_order: 4,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'skill-05',
      portfolio_id: 'omar-portfolio-001',
      name: 'PostgreSQL & Supabase Architecture',
      category: 'Backend & APIs',
      level: 86,
      years: 3,
      sort_order: 5,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'skill-06',
      portfolio_id: 'omar-portfolio-001',
      name: 'WebRTC & Real-time WebSockets',
      category: 'Protocols & Performance',
      level: 85,
      years: 2,
      sort_order: 6,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  experiences: [
    {
      id: 'exp-01',
      portfolio_id: 'omar-portfolio-001',
      company: 'Creative Technology Group',
      position: 'Lead Frontend Engineer & UI Architect',
      location: 'Remote',
      start_date: '2024-01-01',
      current_position: true,
      description:
        'Leading design system engineering, high-performance web applications, and multi-tenant SaaS interfaces. Spearheading modern frontend architectures with TypeScript, React, and Tailwind.',
      technologies: ['React 19', 'TypeScript', 'Tailwind', 'Next.js', 'Vite'],
      sort_order: 1,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'exp-02',
      portfolio_id: 'omar-portfolio-001',
      company: 'Digital Solutions Lab',
      position: 'Full-Stack Developer',
      location: 'Cairo, Egypt',
      start_date: '2022-06-01',
      end_date: '2023-12-31',
      current_position: false,
      description:
        'Architected REST APIs, database schemas, and responsive user interfaces for diverse client platforms across healthcare, e-commerce, and logistics.',
      technologies: ['Node.js', 'Express', 'PostgreSQL', 'React', 'Tailwind'],
      sort_order: 2,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  services: [
    {
      id: 'srv-01',
      portfolio_id: 'omar-portfolio-001',
      title: 'Full-Stack Web Development',
      description:
        'End-to-end modern web applications built with TypeScript, React 19, scalable REST backends, and rock-solid architectures.',
      features: [
        'Single Page Applications (SPA) & Progressive Web Apps',
        'TypeScript-first architecture for absolute reliability',
        'High-speed load times with Lighthouse 95+ scores',
        'REST API design, authentication, and database integration',
      ],
      price: 'Custom Scope',
      currency: 'USD',
      cta: 'Discuss Project',
      active: true,
      sort_order: 1,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'srv-02',
      portfolio_id: 'omar-portfolio-001',
      title: 'UI/UX & Design System Architecture',
      description:
        'Transforming complex digital products into clean, minimalist interfaces with fluid micro-interactions and cohesive design tokens.',
      features: [
        'Modern glassmorphism and balanced visual depth',
        'Accessible, keyboard-navigable component libraries',
        'Dark / Light theme system with persistent preferences',
        'Figma to production-code high fidelity translation',
      ],
      price: 'Custom Scope',
      currency: 'USD',
      cta: 'Explore Designs',
      active: true,
      sort_order: 2,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'srv-03',
      portfolio_id: 'omar-portfolio-001',
      title: 'Technical Consulting & Performance Optimization',
      description:
        'In-depth audits of existing web applications to improve bundle size, Core Web Vitals, responsiveness, and codebase maintainability.',
      features: [
        'Bundle size reduction and code splitting audit',
        'Rendering performance and layout shift (CLS) fixes',
        'Security headers, honeypots, and input sanitization',
        'Architecture refactoring for long-term maintainability',
      ],
      price: 'Custom Scope',
      currency: 'USD',
      cta: 'Schedule Audit',
      active: true,
      sort_order: 3,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  testimonials: [
    {
      id: 'test-01',
      portfolio_id: 'omar-portfolio-001',
      name: 'Alexander Wright',
      role: 'Head of Product',
      company: 'Aether Cloud',
      content:
        'Omar delivered an exceptional frontend experience for our platform. His attention to detail, performance standards, and modern design sense exceeded our expectations.',
      rating: 5,
      published: true,
      sort_order: 1,
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'test-02',
      portfolio_id: 'omar-portfolio-001',
      name: 'Maya Lin',
      role: 'Creative Director',
      company: 'Studio Pulse',
      content:
        'Working with Omar was seamless. The balance of aesthetic glassmorphism and blazing performance is rare to find. Highly recommended for any ambitious web venture.',
      rating: 5,
      published: true,
      sort_order: 2,
      deleted_at: null,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  social_links: [
    {
      id: 'soc-01',
      portfolio_id: 'omar-portfolio-001',
      platform: 'facebook',
      url: 'https://www.facebook.com/omar.mhmdfwzi',
      label: 'Verified Facebook Profile',
      sort_order: 1,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
    {
      id: 'soc-02',
      portfolio_id: 'omar-portfolio-001',
      platform: 'github',
      url: 'https://github.com/omarmhmdfwzi22-hacker',
      label: 'GitHub Repositories',
      sort_order: 2,
      visible: true,
      created_at: '2026-09-20T12:00:00.000Z',
      updated_at: '2026-09-20T12:00:00.000Z',
    },
  ],
  platform_settings: {
    id: 'plat-001',
    platform_name: 'ULTIMATE TOMATO',
    logo_url: './assets/ultimate-tomato-logo.png',
    primary_color: '#F52F3A',
    support_email: 'support@ultimatetomato.com',
    maintenance_mode: false,
    created_at: '2026-09-20T12:00:00.000Z',
    updated_at: '2026-09-20T12:00:00.000Z',
  },
};
